config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  root "home#index"

  namespace :api do
    resources :teams, only: %i[index show create update destroy]
    resources :exploits, only: %i[index show create update destroy]
    resources :flags, only: %i[index create]
  end

  resources :teams, except: %i[show]
  resources :exploits
  resources :flags, only: %i[index new create]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flag.rb
# frozen_string_literal: true

class Flag < ApplicationRecord
  belongs_to :team, optional: true
  belongs_to :exploit, optional: true

  validates :content, :pts, presence: true
  validates :content, uniqueness: true

  enum status: { initial: 0, accepted: 1, already_posted: 2, too_old: 3, our_own: 4 }
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_and_belongs_to_many :exploits
  has_many :flags

  validates :title, :host, presence: true

  enum status: { down: 0, up: 1 }

  after_save do
    exploits.each { |exploit| Engine::Exploit::AfterSave.call(exploit) }
  end
end

app/controllers/api/api_controller.rb
# frozen_string_literal: true

class Api::ApiController < ApplicationController
  before_action :authenticate_request
  skip_before_action :verify_authenticity_token

  private

  def authenticate_request
    head :unauthorized unless api_key_matches?
  end

  def api_key_matches?
    request.headers["HTTP_API_KEY"] == ENV.fetch("API_KEY")
  end
end

app/controllers/api/flags_controller.rb
# frozen_string_literal: true

class Api::FlagsController < ApiController
  def index
    @flags = Flag.all
  end

  def create
    @flag = Flag.new(permitted_params)

    respond_to do |format|
      if @flag.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def permitted_params
    params.fetch(:flag, {}).permit(:content)
  end
end

app/controllers/api/teams_controller.rb
# frozen_string_literal: true

class Api::TeamsController < ApiController
  before_action :set_team, only: [:show, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show; end

  def create
    @team = Team.new(permitted_params)

    respond_to do |format|
      if @team.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @team.update(permitted_params)
        format.json { render :show, status: :ok }
      else
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @team.destroy!
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def permitted_params
    params.fetch(:team, {}).permit(:host, :title, :status)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/flags_controller.rb
# frozen_string_literal: true

class FlagsController < UiController
  before_action :set_flag, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: FlagDatatable.new(params) }
    end
  end

  def show; end

  def new
    @flag = Flag.new
  end

  def edit; end

  def create
    @flag = Flag.new(permitted_params)

    respond_to do |format|
      if @flag.save
        format.html { redirect_to @flag, notice: "Flag was successfully created." }
        format.json { render :show, status: :created, location: @flag }
      else
        format.html { render :new }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flag.update(permitted_params)
        format.html { redirect_to @flag, notice: "Flag was successfully updated." }
        format.json { render :show, status: :ok, location: @flag }
      else
        format.html { render :edit }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flag.destroy!
    respond_to do |format|
      format.html { redirect_to flags_url, notice: "Flag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_flag
    @flag = Flag.find(params[:id])
  end

  def permitted_params
    params.fetch(:flag, {})
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < UiController
  def index
    @charts = Charts::GetData.call.response
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: TeamDatatable.new(params) }
    end
  end

  def show; end

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @team = Team.new(permitted_params)

    if @team.save
      sync_exploits
      respond_to do |format|
        format.html { redirect_to teams_path }
      end
    else
      head :unprocessable_entity
    end
  end

  def update
    if @team.update(permitted_params)
      sync_exploits
      respond_to do |format|
        format.html { redirect_to teams_path }
      end
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @team.destroy!
    head :no_content
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def permitted_params
    params
      .fetch(:team, {})
      .permit(:host, :title, :status, exploit_ids: [])
      .yield_self { |params| Utils.with_numeric_status(params) }
  end

  def sync_exploits
    permitted_params.fetch(:exploit_ids, []).map { |id| @team.exploits << Exploit.find(id) }
  end
end

app/controllers/ui_controller.rb
# frozen_string_literal: true

class UiController < ApplicationController
  http_basic_authenticate_with name: ENV.fetch("UI_USERNAME"), password: ENV.fetch("UI_PASSWORD")
end

app/views/flags/_form.html.erb
<%= form_with(model: flag, local: true) do |form| %>
  <% if flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
      <% flag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flags/edit.html.erb
<h1>Editing Flag</h1>

<%= render 'form', flag: @flag %>

<%= link_to 'Show', @flag %> |
<%= link_to 'Back', flags_path %>

app/views/flags/index.html.slim
= render(partial: 'partials/flags')

app/views/flags/new.html.erb
<h1>New Flag</h1>

<%= render 'form', flag: @flag %>

<%= link_to 'Back', flags_path %>

app/views/flags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flag_path(@flag) %> |
<%= link_to 'Back', flags_path %>

app/views/home/index.html.slim
section class="m-5"
  - @charts[:line_charts].each do |chart|
    div class="mt-3 mb-3"
      div class="card text-center"
        div class="card-body"
          h5 class="card-title" = chart[:title]
          = line_chart chart[:data], legend: :bottom
  - @charts[:pie_charts].each_slice(2) do |chart_group|
    div class="mt-3 mb-3"
      div class="card-deck"
        - chart_group.each do |chart|
          div class="card text-center"
            div class="card-body"
              h5 class="card-title" = chart[:title]
              = pie_chart chart[:data], legend: :left

app/views/layouts/application.html.slim
doctype html
html
  head
    title Hurricane Farm
    = csrf_meta_tag
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render(partial: 'partials/navigation')
    = yield

app/views/partials/_flags.html.slim
section class="m-5"
  table id="flags-datatable" class="table table-striped table-bordered"
    thead
      tr
        th scope="col" ID
        th scope="col" Created At
        th scope="col" Team
        th scope="col" Exploit
        th scope="col" Content
        th scope="col" Status
        th scope="col" Points
    tbody

javascript:
  const tableSelector = '#flags-datatable';
  const table = $(tableSelector).DataTable({
    processing: true,
    serverSide: true,
    ajax: {
      url: $(tableSelector).data('source')
    },
    stateSave: true,
    buttons: ['refresh'],
    pagingType: 'full_numbers',
    columns: [
      {"data": "id"},
      {"data": "created_at"},
      {"data": "team"},
      {"data": "exploit"},
      {"data": "content"},
      {"data": "status"},
      {"data": "pts"},
    ],
    order: [0, 'desc'],
    initComplete: () => table.buttons().container().prependTo($('.col-md-6:eq(1)'))
  });

app/views/partials/_navigation.html.slim
nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top"
  a class="navbar-brand" href="/" Hurricane Farm
  div class="collapse navbar-collapse"
    div class="navbar-nav"
      a class="nav-item nav-link" href="/teams" data-turbolinks="false" Teams
      a class="nav-item nav-link" href="/exploits" data-turbolinks="false" Exploits
      a class="nav-item nav-link" href="/flags" data-turbolinks="false" Flags

app/views/partials/_teams.html.slim
section class="m-5"
  = render 'teams/new'
  = render 'teams/edit'
  table id="teams-datatable" class="table table-striped table-bordered"
    thead
      tr
        th scope="col" ID
        th scope="col" Title
        th scope="col" Host
        th scope="col" Active
        th scope="col" Exploits
        th scope="col" Team Graph
        th scope="col" Points Gained
        th scope="col" Edit Link
    tbody

javascript:
  const tableSelector = '#teams-datatable';
  const table = $(tableSelector).DataTable({
    processing: true,
    serverSide: true,
    ajax: {
      url: $(tableSelector).data('source')
    },
    buttons: ['refresh'],
    pagingType: 'full_numbers',
    columns: [
      { data: "id" },
      { data: "title" },
      { data: "host" },
      {
        data: "status",
        render: data => `<img src="https://icongr.am/material/${data === 'up' ? 'check' : 'close'}.svg" />`
      },
      {
        data: "exploits",
        render: data => JSON.parse(data).map(val => `<img src="https://icongr.am/material/flash${val === 1 ? '' : '-off'}.svg?size=18" />`).join('')
      },
      { data: "flags", orderable: false, searchable: false },
      { data: "points", orderable: false, searchable: false },
      {
        data: "edit_link",
        render: data => `<a href="${data}" data-remote="true" data-toggle="modal" data-target="#edit-modal"><img src="https://icongr.am/material/account-edit.svg" /></a>`,
        orderable: false,
        searchable: false
      }
    ],
    columnDefs: [
      {
        targets: [0, 1, 2, 3, 4, 5, 6, 7],
        className: 'text-center align-middle'
      }
    ],
    order: [0, 'asc'],
    initComplete: () => {
      table.buttons().container().prependTo($('.col-md-6:eq(1)'));
      $(`<a href="/teams/new" data-remote="true" data-toggle="modal" data-target="#new-modal"><button class="btn btn-secondary" tabindex="0" aria-controls="teams-datatable" type="button"><span>New Team</span></button></a>`).prependTo($('.dt-buttons'));
    }
  });